# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "OPENSchool Solutions | Dynamic learning for a tailored experience"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Enable every school to become an OPENSchool. Dynamic learning for a tailored experience"


# The subpath of your site, e.g. /blog, for generating urls
baseurl: 

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://openschoolsolutions.github.io"

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "John Choque"

# Social links in the site footer
twitter_username: ""
facebook_username: ""
googleplus_username: ""
pinterest_username: ""
linkedin_username: ""
